---
title: "Introduction"
format: html
editor: visual
css: www/hms_quarto-style.css
---

Highly migratory species (HMS) include some of the most commercially valuable species on the planet. Conglomerates such as tuna, billfishes such as swordfish, and sharks net tens of billions of dollars a year in domestic trade, landing, and processing value. Multiple nations collaborate to manage HMS due to the transience of their habitat (e.g., migrating in and out of national waters). The high value and international consideration of HMS fisheries compel analysis of dynamics through time in the domestic market to ensure the sustainability of the fisheries from an economic lens.

The National Oceanic and Atmospheric Administration (NOAA) has surveyed and collected data from fishers, processors, and ports along the seafood supply chain for decades. End-users of these data include fisheries managers, scientists, and economists interested in short- and long-term trends in catch and consumption of both domestic and foreign seafood species at regional and national levels. The NOAA provides federal fisheries data at the [Fisheries One-Stop Shop](https://www.fisheries.noaa.gov/foss/f?p=215:200::::::) (FOSS), a public-facing online repository kept and maintained by the NOAA. The FOSS enables anyone with an internet connection to access fisheries data deemed non-confidential (as protected by the Magnuson-Stevens Fisheries Conservation and Management Act, MSA, of 1976) since the 1980s. Despite public access, the FOSS lacks summarizing tools that users within and outside of the fisheries science space would otherwise need to gain quantitative information from the data in a relatively short amount of time. This can be an issue for fisheries scientists and economists seeking answers to straightforward questions as well as public users perhaps curious about fisheries but lacking data science skills.

The NOAA Fisheries Highly Migratory Species Seafood Dashboard summarizes the landing, processing, and trade of 25 highly migratory species over the last twenty years. Users can investigate the value, volume and price of domestically landed, processed, or traded HMS and their conglomerates. The metrics visualized in this dashboard largely draw from [Fissel et al.'s study in 2023](https://spo.nmfs.noaa.gov/sites/default/files/pdf-content/mfr841-21_1.pdf) that explored characteristics of U.S. trade of seafood species with significant domestic commercial interest. We source some of our data from the same NOAA database sourced by the FOSS rather than from the FOSS directly due to heightened data resolution not currently available in the FOSS. While we continue to maintain the same data confidentiality standards outlined by the MSA, withheld data may cause underestimates.
